/**
 * The local, offline provider.
 *
 * Makes zero network calls, requires no API key and costs nothing. It exists to
 * prove the architecture end to end — orchestrator, flags, validation, error
 * handling, logging and the HTTP route can all be exercised and tested without a
 * vendor account.
 *
 * The responses are placeholders and say so. No attempt is made to produce
 * business-quality screening or ranking output: inventing plausible-looking
 * analysis here would be worse than useless, because it would be indistinguishable
 * from the real thing in a screenshot while being entirely fabricated.
 *
 * Output is fully deterministic — same request in, same object out. No clock, no
 * randomness, no counters. That is what lets the tests assert equality on a whole
 * response rather than poking at individual fields.
 */
const { AIProvider } = require('./AIProvider');

const PROVIDER_NAME = 'mock';
const MODEL_NAME = 'mock-v1';

/** One fixed line per mode, matching the mode ids in `ai/modes/agentModes.js`. */
const MODE_CONTENT = Object.freeze({
  assistant: 'Mock Recruitment Assistant is active.',
  screening: 'Mock screening response generated successfully.',
  ranking: 'Mock ranking response generated successfully.',
  comparison: 'Mock comparison response generated successfully.',
  insights: 'Mock insights response generated successfully.'
});

class MockAIProvider extends AIProvider {
  constructor() {
    super({ name: PROVIDER_NAME, model: MODEL_NAME });
  }

  /**
   * @param {import('../types/ai.types').AIRequest} request
   * @returns {Promise<import('../types/ai.types').AIProviderResult>}
   */
  async run(request) {
    const { mode, message, context } = request;

    const content = MODE_CONTENT[mode];
    if (!content) {
      // Unreachable through the orchestrator, which validates the mode first.
      // Kept so a future caller that skips validation fails loudly here rather
      // than returning an empty response.
      throw new Error(`MockAIProvider has no canned response for mode "${mode}".`);
    }

    return {
      mode,
      content,
      // Echoes only what it was given, and only sizes and identifiers — never the
      // message text. A mock that reflected its input back would make it easy to
      // ship a "working" feature that is really just an echo.
      structuredData: {
        placeholder: true,
        note: 'Generated by the mock provider. No analysis was performed and no model was called.',
        receivedMessageLength: typeof message === 'string' ? message.length : 0,
        jobId: context.jobId,
        candidateCount: context.candidateIds.length,
        filterKeys: Object.keys(context.filters).sort()
      },
      provider: PROVIDER_NAME,
      model: MODEL_NAME,
      usage: AIProvider.emptyUsage()
    };
  }
}

module.exports = { MockAIProvider, PROVIDER_NAME, MODEL_NAME, MODE_CONTENT };
